general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true

model_list:

  # Common use cases, models assigned by use case as name
  - model_name: chat-completion
    litellm_params:
      model: claude-3-7-sonnet-20250219

  - model_name: code-agent
    litellm_params:
      model: claude-3-7-sonnet-20250219

  - model_name: code-fim-completion
    litellm_params:
      model: openrouter/google/gemini-2.5-flash-preview

  # General Models by Vendor & Name 
  - model_name: anthropic-claude-3.7-sonnet
    litellm_params:
      model: claude-3-7-sonnet-20250219

  - model_name: anthropic-claude-4-opus
    litellm_params:
      model: claude-opus-4-20250514
 
  - model_name: anthropic-claude-4-sonnet
    litellm_params:
      model: claude-sonnet-4-20250514

  - model_name: google-gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro-preview-05-06

  - model_name: groq-deepseek-70b
    litellm_params:
      model: groq/deepseek-r1-distill-llama-70b

  - model_name: openai-gpt4-turbo
    litellm_params:
      model: openai/gpt-4.1

  - model_name: ollama-deepcoder-14b
    litellm_params:
      model: ollama/deepcoder:14b
      base_url: http://ollama:11434

  - model_name: ollama-gemma-3-12b
    litellm_params:
      model: ollama/gemma3:12b-it-qat
      base_url: http://ollama:11434

  - model_name: ollama-qwen-2.5-coder-7b
    litellm_params:
      model: ollama/qwen2.5-coder:7b
      base_url: http://ollama:11434

  - model_name: ollama-qwen-3-14b
    litellm_params:
      model: ollama/qwen3:14b
      base_url: http://ollama:11434

  - model_name: openrouter-gemini-2.5-flash
    litellm_params:
      model: openrouter/google/gemini-2.5-flash-preview
 
  - model_name: openrouter-gemini-2.5-flash-thinking
    litellm_params:
      model: openrouter/google/gemini-2.5-flash-preview:thinking
